/**
 * App shell semantics smoke — keeps the shared shell connectivity signal small.
 * Run: node --experimental-strip-types scripts/app_shell_semantics_smoke.mts
 */

import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import path from 'node:path'

const repoRoot = path.resolve(import.meta.dirname, '..')
const appCode = readFileSync(path.join(repoRoot, 'frontend/src/App.tsx'), 'utf8')
const onboardingCode = readFileSync(path.join(repoRoot, 'frontend/src/components/PublicBetaOnboarding.tsx'), 'utf8')
const apiCode = readFileSync(path.join(repoRoot, 'frontend/src/lib/api.ts'), 'utf8')
const dictCode = readFileSync(path.join(repoRoot, 'frontend/src/i18n/dict.ts'), 'utf8')
const stylesCode = readFileSync(path.join(repoRoot, 'frontend/src/styles.css'), 'utf8')
const packageJson = readFileSync(path.join(repoRoot, 'frontend/package.json'), 'utf8')

assert.match(appCode, /import \{ bootstrapDemoWorkspace, getAuthConfigCheck, getBackendHealth, getBackendReadiness, getDemoWorkspaceStatus, getTopologyFreshness, getWorkspaces \} from '\.\/lib\/api'/, 'App shell should import backend liveness, readiness, auth config-check, demo status, topology freshness, and workspaces for global connectivity')
assert.match(appCode, /getAuthConfigCheck/, 'App shell should surface auth readiness globally')
assert.match(apiCode, /getCurrentAuthSession/, 'API helper for current auth session should exist')
assert.match(apiCode, /disableOwnAccount/, 'API helper for account disable route should exist')
assert.match(apiCode, /new Headers\(init\.headers\)/, 'Bearer auth helper should avoid persisting tokens in app state')
assert.match(apiCode, /headers\.set\('Authorization', `Bearer \$\{token\}`\)/, 'Bearer auth helper should pass caller-provided tokens only in request headers')
assert.match(appCode, /AuthConfigCheckResponse/, 'App shell should retain typed auth config-check details for account lifecycle readiness')
assert.match(appCode, /AccountLifecycleReadiness/, 'App shell should render a provider-safe account lifecycle readiness panel')
assert.match(appCode, /data-testid="account-lifecycle-readiness"/, 'Account lifecycle readiness panel should be test-addressable')
assert.match(appCode, /data-testid="account-lifecycle-pill-row"/, 'Account lifecycle readiness pills should be test-addressable')
assert.match(appCode, /accountManagementGated = lifecycle\?\.account_management_enabled === false/, 'Account management readiness should treat missing data as pending')
assert.match(appCode, /publicRoutesExposureGated = lifecycle\?\.public_routes_exposure_gated === true/, 'Public route exposure readiness should treat missing data as pending')
assert.match(appCode, /public_beta_shared_gate_satisfied/, 'Account lifecycle readiness should surface shared limiter evidence status')
assert.match(appCode, /accountLifecycle\.pill\.publicRoutesGated/, 'Account lifecycle panel should use i18n keys for public-route exposure copy')
assert.match(dictCode, /'accountLifecycle\.title':/, 'Account lifecycle title i18n key should exist')
assert.match(dictCode, /'accountLifecycle\.pill\.publicRoutesGated':/, 'Account lifecycle public-route gate i18n key should exist')
assert.match(dictCode, /'accountLifecycle\.pill\.sharedLimiter':/, 'Account lifecycle shared limiter i18n key should exist')
assert.match(appCode, /getBackendReadiness/, 'App shell should require backend readiness in the global backend signal')
assert.match(appCode, /getTopologyFreshness/, 'App shell should surface topology freshness globally')
assert.match(appCode, /getDemoWorkspaceStatus/, 'App shell should surface demo workspace readiness globally')
assert.match(appCode, /bootstrapDemoWorkspace/, 'Public beta onboarding CTA should bootstrap the demo workspace idempotently')
assert.match(appCode, /type BackendConnectivityStatus = 'checking' \| 'online' \| 'offline'/, 'Connectivity status union should stay small')
assert.match(appCode, /type AuthConnectivityStatus = 'checking' \| 'ready' \| 'not-configured'/, 'Auth connectivity status union should be defined')
assert.match(appCode, /type TopologyFreshnessStatus = 'checking' \| 'fresh' \| 'stale' \| 'empty'/, 'Topology freshness status union should be defined')
assert.match(appCode, /window\.setInterval\(refreshBackendConnectivity, 30000\)/, 'Backend connectivity should refresh on a bounded interval')
assert.match(appCode, /window\.setInterval\(refreshAuthConnectivity, 30000\)/, 'Auth connectivity should refresh on a bounded interval')
assert.match(appCode, /window\.setInterval\(refreshTopologyFreshness, 60000\)/, 'Topology freshness should refresh on a bounded interval')
assert.match(appCode, /data-testid="app-shell-header"/, 'App shell should expose a test-addressable header container')
assert.match(appCode, /data-testid="app-view-toggle"/, 'View toggle should be test-addressable inside the compact header')
assert.match(appCode, /data-testid="app-connectivity-row"/, 'Connectivity row should be test-addressable inside the compact header')
// Redesign directive #4: the connection-status/onboarding/account-lifecycle panels are removed from
// the header; status collapses to the single "정상" health pulse. The readiness meta-chip toggle and
// the shared expanded-panels container no longer exist in the slim top bar.
assert.doesNotMatch(appCode, /data-testid="app-shell-meta-chips"/, 'Redesign #4: slim header should no longer carry the readiness meta-chip toggle')
assert.doesNotMatch(appCode, /id="app-shell-expanded-panels"/, 'Redesign #4: header should no longer embed the expanded onboarding/lifecycle panels')
assert.match(appCode, /className="app-onboarding-banner"/, 'Public beta onboarding should relocate to a first-run body banner below the slim top bar')
assert.match(appCode, /view-toggle-compact/, 'App shell should apply compact view-toggle modifier')
assert.match(appCode, /lang-toggle-compact/, 'App shell should apply compact lang-toggle modifier')
assert.match(appCode, /workspace-header-row workspace-header-row-primary/, 'App shell should render a primary header row')
assert.match(appCode, /workspace-header-row workspace-header-row-secondary/, 'App shell should render a secondary header row')
assert.match(stylesCode, /\.workspace-header-inner-compact/, 'Compact header inner CSS should exist')
assert.match(stylesCode, /\.workspace-header-row-primary/, 'Primary header row CSS should exist')
assert.match(stylesCode, /\.workspace-header-row-secondary/, 'Secondary header row CSS should exist')
assert.doesNotMatch(stylesCode, /\.workspace-header-meta-chip/, 'Redesign #4: dead meta-chip CSS is removed alongside the header toggle it styled')
assert.match(stylesCode, /\.view-toggle-compact/, 'Compact view-toggle CSS should exist')
assert.match(stylesCode, /\.lang-toggle-compact/, 'Compact lang-toggle CSS should exist')
assert.match(appCode, /aria-live="polite"/, 'Connectivity row should announce status changes politely')
assert.match(appCode, /role="status"/, 'Manual refresh result message should expose status semantics')
assert.match(appCode, /backendLabels\[backendConnectivity\]/, 'Connectivity row should render backend status via i18n')
assert.match(appCode, /authLabels\[authConnectivity\]/, 'Connectivity row should render auth status via i18n')
assert.match(appCode, /freshnessLabels\[topologyFreshness\]/, 'Connectivity row should render topology freshness via i18n')
assert.match(appCode, /workspace-connectivity-group/, 'Workspace connectivity group should be present')
assert.match(appCode, /workspace-connectivity-sep/, 'Workspace connectivity separator should be present')
assert.match(appCode, /handleRefreshConnectivity/, 'App shell should expose a manual connectivity refresh handler')
assert.match(appCode, /connectivityRefreshing/, 'Manual connectivity refresh should guard duplicate clicks')
assert.match(appCode, /disabled=\{connectivityRefreshing\}/, 'Manual connectivity refresh button should disable while refreshing')
assert.match(appCode, /aria-busy=\{connectivityRefreshing\}/, 'Manual connectivity refresh button should expose busy state')
assert.match(appCode, /data-testid="app-connectivity-refresh"/, 'Connectivity row should render a test-addressable manual refresh button')
assert.match(onboardingCode, /data-testid="public-beta-onboarding"/, 'App shell should expose a test-addressable public beta onboarding card')
assert.match(appCode, /data-testid="public-beta-demo-badge"/, 'App shell should expose a test-addressable demo readiness badge')
assert.match(onboardingCode, /data-testid="public-beta-demo-cta"/, 'Public beta demo CTA should be test-addressable')
assert.match(onboardingCode, /data-testid="public-beta-onboarding-toggle"/, 'Public beta onboarding should expose a test-addressable collapse/expand toggle')
assert.match(onboardingCode, /data-testid="public-beta-onboarding-body"/, 'Public beta onboarding should expose a test-addressable collapsible body region')
assert.match(onboardingCode, /aria-expanded=\{expanded\}/, 'Public beta onboarding toggle should expose aria-expanded')
assert.match(onboardingCode, /data-expanded=\{expanded \? 'true' : 'false'\}/, 'Public beta onboarding should expose expanded state via data attribute')
assert.match(onboardingCode, /hidden=\{!expanded\}/, 'Public beta onboarding body should be hidden when collapsed')
assert.match(appCode, /data-testid="account-lifecycle-readiness-toggle"/, 'Account lifecycle readiness should expose a test-addressable collapse/expand toggle')
assert.match(appCode, /data-testid="account-lifecycle-readiness-body"/, 'Account lifecycle readiness should expose a test-addressable collapsible body region')
assert.match(appCode, /data-testid="account-lifecycle-mini-pill"/, 'Account lifecycle readiness should expose a compact mini-pill in collapsed state')
assert.match(dictCode, /'shell\.metaSection\.expand'/, 'App shell should register an i18n key for the expand copy')
assert.match(dictCode, /'shell\.metaSection\.collapse'/, 'App shell should register an i18n key for the collapse copy')
assert.match(dictCode, /'shell\.metaSection\.summary\.lifecycleReady'/, 'App shell should register an i18n key for collapsed lifecycle summary')
// The onboarding banner now owns a local expand/collapse state instead of the removed shared
// header meta-section state (metaCollapsed/metaExpanded and the lifecycle share were removed with the panels).
assert.match(appCode, /const \[onboardingExpanded, setOnboardingExpanded\] = useState<boolean>\(true\)/, 'Onboarding banner should own a local expand/collapse state')
assert.doesNotMatch(appCode, /metaExpanded/, 'Redesign #4: shared meta-expanded derivation should be removed with the header panels')
assert.match(appCode, /const isFirstRun = workspaceCount === 0 && topologyFreshness === 'empty'/, 'Public beta onboarding should derive first-run state from empty workspace and empty topology')
assert.match(onboardingCode, /data-first-run=\{isFirstRun \? 'true' : 'false'\}/, 'Public beta onboarding should expose first-run state for browserless and UI tests')
assert.match(onboardingCode, /isFirstRun \? t\('publicBeta\.firstRun\.title'\) : t\('publicBeta\.title'\)/, 'Public beta onboarding should render conditional first-run title copy')
assert.match(appCode, /setViewMode\('topology'\)/, 'Public beta onboarding CTA should send first-run users to the topology demo path')
assert.match(appCode, /handleOpenDemoPath/, 'Public beta onboarding CTA should use a dedicated demo bootstrap handler')
assert.match(onboardingCode, /t\('publicBeta\.cta\.status'\)/, 'Public beta onboarding should expose a readiness refresh CTA')
assert.match(appCode, /Promise\.allSettled/, 'Manual refresh should update backend, auth, and topology signals together')
assert.match(appCode, /backendReadinessResult\.value\.checks\.database/, 'Manual backend signal should require database readiness')
assert.match(appCode, /Promise\.all\(\[getBackendHealth\(\), getBackendReadiness\(\)\]\)/, 'Periodic backend signal should require liveness and readiness together')
assert.match(appCode, /workspaces\.length === 0\)[\s\S]*?setTopologyFreshness\('empty'\)[\s\S]*?setTopologyNodeCount\(null\)/, 'Topology freshness polling should clear stale node counts when no workspace is available')
assert.match(appCode, /<PublicBetaOnboarding/, 'App shell should delegate public beta onboarding rendering to a focused component')
assert.match(packageJson, /app_shell_semantics_smoke\.mts/, 'frontend smoke:semantics should include this app-shell smoke')

assert.match(stylesCode, /\.workspace-connectivity-row/, 'Connectivity row CSS should exist')
assert.match(stylesCode, /\.connectivity-dot\.online/, 'Online connectivity dot CSS should exist')
assert.match(stylesCode, /\.connectivity-dot\.checking/, 'Checking connectivity dot CSS should exist')
assert.match(stylesCode, /\.connectivity-dot\.offline/, 'Offline connectivity dot CSS should exist')
assert.match(stylesCode, /\.workspace-connectivity-refresh/, 'Manual connectivity refresh button CSS should exist')
assert.match(stylesCode, /\.workspace-connectivity-refresh:disabled/, 'Manual connectivity refresh disabled CSS should exist')
assert.match(stylesCode, /\.public-beta-onboarding\.collapsed/, 'Collapsed public beta onboarding CSS should exist')
assert.match(stylesCode, /\.public-beta-onboarding\.expanded/, 'Expanded public beta onboarding CSS should exist')
assert.match(stylesCode, /\.public-beta-onboarding\.first-run/, 'First-run public beta onboarding variant CSS should exist')
assert.match(stylesCode, /\.public-beta-onboarding-summary/, 'Public beta onboarding summary button CSS should exist')
assert.match(stylesCode, /\.public-beta-onboarding-chevron/, 'Public beta onboarding chevron CSS should exist')
assert.match(stylesCode, /\.public-beta-onboarding-body > \.public-beta-actions/, 'Public beta onboarding body actions should be grid-placed in expanded state')
assert.match(stylesCode, /\.account-lifecycle-readiness\.collapsed/, 'Collapsed account lifecycle readiness CSS should exist')
assert.match(stylesCode, /\.account-lifecycle-readiness\.expanded/, 'Expanded account lifecycle readiness CSS should exist')
assert.match(stylesCode, /\.account-lifecycle-readiness-summary/, 'Account lifecycle readiness summary button CSS should exist')
assert.match(stylesCode, /\.account-lifecycle-mini-pill\.ready/, 'Account lifecycle mini-pill ready CSS should exist')
assert.match(stylesCode, /\.account-lifecycle-mini-pill\.pending/, 'Account lifecycle mini-pill pending CSS should exist')
assert.match(stylesCode, /prefers-reduced-motion/, 'First-run onboarding animation should respect reduced-motion preference')
assert.match(stylesCode, /\.public-beta-actions/, 'Public beta onboarding actions CSS should exist')
assert.match(stylesCode, /\.public-beta-demo-badge/, 'Demo readiness badge CSS should exist')
assert.match(stylesCode, /\.public-beta-demo-badge\.ready/, 'Demo readiness badge ready CSS should exist')
assert.match(stylesCode, /\.account-lifecycle-readiness/, 'Account lifecycle readiness CSS should exist')
assert.match(stylesCode, /\.account-lifecycle-pill\.ready/, 'Account lifecycle ready pill CSS should exist')
assert.match(stylesCode, /\.account-lifecycle-pill\.pending/, 'Account lifecycle pending pill CSS should exist')

console.log('✅ app_shell_semantics_smoke.mts: all assertions passed')
